language: go

stage: test
install:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - mkdir -p ${GOPATH}/src/github.com/terraform-providers
  - cd ${GOPATH}/src/github.com/terraform-providers
  - git clone https://github.com/terraform-providers/terraform-provider-aws.git
  - export AWS_PROVIDER_PATH=$GOPATH/src/github.com/terraform-providers/terraform-provider-aws
  - go get ./...
  - cd ${TRAVIS_HOME}
script:
  - go install ${AWS_PROVIDER_PATH}/awsproviderlint
  - ./run_checks.sh
  - git checkout master
  - git add ./results/*
  - git add README.md
  - git commit -m "Update static checks with build $TRAVIS_BUILD_NUMBER"
  - git remote add commit-origin https://${GH_TOKEN}@github.com/YakDriver/terraform-test-conventions.git > /dev/null 2>&1
  - git push --quiet --set-upstream commit-origin master 
